# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  databaseServerName: server4000

steps:
  - script: |
      echo $(databaseServerName)
  # Use bash or powershell to change the value or set the variable
  # This can be use to change the value of a variable within a stage or job.
  # This is render at runtime
  - bash: echo "##vso[task.setvariable variable=databaseServerName]server5000"
  - script: |
      echo $(databaseServerName) 
  # This will give the initial variable value as the expresion below is render at compile time i.e befoe run time.
  - script: |
      echo ${{ variables.databaseServerName }}